# Generated by Django 4.0 on 2021-12-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название создателя игры')),
            ],
            options={
                'verbose_name': 'Создатель игры',
                'verbose_name_plural': 'Создатели игры',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя участника')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
                ('interests', models.CharField(max_length=300, verbose_name='Интересы')),
                ('letter', models.TextField(verbose_name='Письмо санте')),
                ('slug', models.SlugField()),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название игры')),
                ('price', models.DecimalField(decimal_places=2, default=1000, max_digits=9, verbose_name='Цена')),
                ('draw_date', models.DateField(default='31.12.2021', verbose_name='Дата жеребьёвки')),
                ('gift_date', models.DateField(verbose_name='Дата отправки подарка')),
                ('slug', models.SlugField()),
                ('game_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='game.gamecreator', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_discription', to='game.game', verbose_name='Игра')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_giver', to='game.player', verbose_name='Кто дарит')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_recipient', to='game.player', verbose_name='Кому дарит')),
            ],
            options={
                'verbose_name': 'Жеребьевка',
                'verbose_name_plural': 'Жеребьевки',
            },
        ),
    ]
