# Generated by Django 4.0 on 2021-12-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='draw_date',
            field=models.DateField(default='2021-12-31', verbose_name='Дата жеребьёвки'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9, verbose_name='Стоимость подарка'),
        ),
        migrations.AlterField(
            model_name='gamecreator',
            name='name',
            field=models.CharField(default='Santa', max_length=100, verbose_name='Название создателя игры'),
        ),
    ]
