# Generated by Django 4.0 on 2021-12-24 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game', '0005_remove_registration_email_remove_registration_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecreator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='player_name',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='price',
            new_name='price_limit',
        ),
        migrations.AddField(
            model_name='game',
            name='game_creator_assistent',
            field=models.ManyToManyField(blank=True, related_name='creator_assistant', to='game.Player', verbose_name='Помощник'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='reg_date_limit',
            field=models.DateField(default='2021-12-30', verbose_name='Последний день регистрации'),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Почтовый адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='gift_reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_reciever', to='game.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='message_to_santa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='wishlist',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='auth.user', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя игрока'),
        ),
        migrations.DeleteModel(
            name='Draw',
        ),
        migrations.DeleteModel(
            name='GameCreator',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
