# Generated by Django 4.0 on 2021-12-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_limit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9, null=True, verbose_name='Стоимость подарка'),
        ),
    ]
