# Generated by Django 4.0 on 2021-12-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_price_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.IntegerField(verbose_name='Пароль для входа в игру')),
                ('slug', models.SlugField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Пароли',
                'verbose_name_plural': 'Пароль',
            },
        ),
    ]
