# Generated by Django 4.0 on 2021-12-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gamepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='reg_date_limit',
        ),
    ]
