# Generated by Django 4.0 on 2021-12-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_rename_password_gamepassword_game_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepassword',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.game', verbose_name='Игра'),
        ),
    ]
