# Generated by Django 4.0 on 2021-12-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_price_limit_alter_player_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_limit',
            field=models.IntegerField(blank=True, choices=[('1', '500'), ('2', '1000'), ('3', '1500'), ('4', '2000')], null=True, verbose_name='Стоимость подарка'),
        ),
    ]
