# Generated by Django 4.0 on 2021-12-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_game_price_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price_limit',
            field=models.CharField(blank=True, choices=[('1', '500'), ('2', '1000'), ('3', '1500'), ('4', '2000')], max_length=5, null=True, verbose_name='Стоимость подарка'),
        ),
    ]
