# Generated by Django 4.0 on 2021-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_game_price_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='invitation_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта для отправки приглашения'),
        ),
    ]
