# Generated by Django 4.0 on 2021-12-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_game_invitation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='player',
            name='slug',
        ),
        migrations.AlterField(
            model_name='player',
            name='gift_reciever',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почтовый адрес получателя подарка'),
        ),
    ]
